# Generated by Django 3.1.6 on 2021-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='english', max_length=200),
            preserve_default=False,
        ),
    ]
